### ISSUE TITLE
Disable hillshades overlay as default

### ISSUE THREAD

**Issue by skjeggape** [ChristopheSeg/J-TrackGallery#24]
My webpage is primarily for norway, sadly just north of Oslo ther are no hillshades, this leaves a wierd looking line. I want to disable this as default, but am unable to finde a logical place to do this.

![jtrack hillshades map bug](https://cloud.githubusercontent.com/assets/13901439/9418894/ad8f3e12-4857-11e5-91b7-e0bc0a921369.png)

**Comment by ChristopheSeg** [comment]
This feature is not implemented. Overlays should be managed in the backend, but hillshade has been added directly in the code so it can be disable. 
I will temporarily add a disable hillshade soon

As a workaround, if you can modify php code, this is a temporary solution: 
-edit file /components/com_jtg/helpers/gpsClass.php
- find the line              $return .= "olmap.addLayer( hs2,hs2_1 );\n";
- comment this line 		// $return .= "olmap.addLayer( hs2,hs2_1 );\n";

In the future, overlays should by managed in the backend so that anyone can add its own hillshade or overlay.

**Comment by skjeggape** [comment]
Wonderful I'll try and patch my webpage later today. 

Also hope to finish translation to norwegian. Can i send it here as a pull request?

**Comment by ChristopheSeg** [comment]
Great for Norwegian translation. You can send them as a pull request (never deal with pull request on Github but that the best way to) You can also send them by email at christophe@jtrackgallery.net

For Hillshade JTrackGallery 0.9.15 has a "disable hillshade" feature (go to backend, config, default parameters, basic configuration tab)

**Comment by skjeggape** [comment]
Wonderful, I'll try and finalise transaltion this evening and send a pull
request 😊
25. aug. 2015 23.09 skrev "Christophe S." <notifications@github.com>:

**Comment by ChristopheSeg** [comment]
Did you start translating? I know this is a long process. If you are interested, I can put those key you translated on Transifex so that you could finish translating on Transifex.com. If you are interested in translating on Transifex, just send me your files; even if your translation is partial. 

Regards, Christophe
